### PR TITLE
 Send for Bulk Mail

### PR DESCRIPTION
**Pull request by pouu69**
i'll make Send for Bulk Mail

### CODE REVIEW

**Comment by pouu69** [comment]
why can't i pull request ?

**Comment by johannesschobel** [comment]
there is already a "batch send" method?!

**Comment by pouu69** [comment]
where is batch send??

**Comment by johannesschobel** [comment]
Sorry, I am currently on the move.. Take a look at the readme > usage >
Message > Message options

There should be a block dealing with "batch sending".. I have, however,
never tried and used it..

Cheers

Am 02.10.2016 3:42 nachm. schrieb "KwanUngPark" <notifications@github.com>:

**Comment by pouu69** [comment]
All I'm saying is different haves you made.
I am the ability to send e-mail, respectively.
Recipients, respectively

http://blog.mailgun.com/the-php-sdk-the-first-of-many-official-mailgun-sdks/ 
check **Batch Message** section

**Comment by Bogardo** [comment]
Please take a look at:
[Batch Sending Mail Issue #50](https://github.com/Bogardo/Mailgun/issues/50)
[Issue using To foreach loop #31](https://github.com/Bogardo/Mailgun/issues/31)
[Support for recipient variables #34](https://github.com/Bogardo/Mailgun/issues/34)

Wouldn't that fix the issue?

**Comment by pouu69** [comment]
ah.. yeah okay i got it.
already made it
sorry. i didn't check issue list.

**Comment by Bogardo** [comment]
@pouu69 No problem!

**Pull request closed without merging**
